#
#   http://wiki.ros.org/costmap_2d
#

global_costmap:
# Coordinate frame and tf parameters
    # 代价地图应该运行的坐标系
    global_frame: map
    # 机器人的基座的坐标系
    robot_base_frame: base_link
    # Specifies the delay in transform (tf) data that is tolerable in seconds.
    transform_tolerance: 0.2

# Rate parameters
    # 全局地图更新的频率
    update_frequency: 5.0
    # 确定代价地图发布可视化信息的速率
    publish_frequency: 2.0
    # 是否由map_server提供的地图服务来进行代价地图的初始化
    static_map: true

# 