{'controller_freq': 20.0, 
'angle_gain': -1.8, 
'Vcmd': 0.7, 
'Lrv': 10.0, 
'L': 0.26, 
'base_speed': 1.0, 
'lfw': 0.13, 
'groups'} : {'parent': 0, 
'angle_gain': -1.8, 
'Vcmd': 0.7, 
'L': 0.26, 
'lfw': 0.13, 
'groups': {}, 
'lrv': 10.0, 
'gas_gain': 1.0, 
'id': 0, 
'controller_freq': 20.0, 
'name': 'Default', 
'parameters': {}, 
'base_speed': 1.0, 
'state': True, 
'Lrv': 10.0, 
'type': '', 
'base_angle': 0.0}, 
'lrv': 10.0, 
'gas_gain': 1.0, 
'base_angle': 0.0}
