#map_type: voxel
map_type: costmap
# robot_radius: 0.3 #»úÆ÷ÈËµÄ°ë¾¶£¬µ¥Î»ÊÇÃ×£¬·ÇÔ²ÐÎ»úÆ÷ÈË»¹ÐèÒªÅäºÏfootprint²ÎÊý
# footprint: [[0.325,0.225],[0.325,-0.225],[-0.325,-0.225],[-0.325,0.225]] #ËÄ±ßÐÎ³µË³ÊÆÕëÄæÊ±Õë×ø±ê¶¼¿ÉÒÔ
footprint: [[0.325,0.270],[0.325,-0.270],[-0.325,-0.270],[-0.325,0.270]]
recovery_behavior_enabled: true
reset_distance: 7.0 #ples of Different Parameterizations
controller_frequency: 5

obstacle_layer: #ÕÏ°­Îï²ã
  enabled:              true
  combination_method:   1
  track_unknown_space:  false
  origin_z: 0.0
  z_voxels: 20
  z_resolution: 0.1
  unknown_cost_value: 0
  unknown_threshold: 8
  mark_threshold: 0
  publish_voxel_map: false

  obstacle_range: 2.5
  raytrace_range: 10.0
  footprint: [[0.325,0.270],[0.325,-0.270],[-0.325,-0.270],[-0.325,0.270]]
  inflation_radius: 0.3
  #inf_is_valid:true
  max_obstacle_height: 0.40
  min_obstacle_height: 0.03
  controller_frequency: 5
  observation_sources: scan 
  #point_cloud_sensor

  scan: {sensor_frame: base_link,  observation_persistence: 0.0, 
  max_obstacle_height: 0.3, min_obstacle_height: 0.05, data_type: LaserScan, topic: /scan, 
  marking: true,clearing: true}

inflation_layer: #ÅòÕÍ²ä
 enabled:              true
 cost_scaling_factor:  5.0   # exponential rate at which the obstacle cost drops off (default:10)
 inflation_radius:     0.23 #ÅòÕÍ°ë¾¶ max. distance from an obstacle at which costs are incurred for planning paths.

static_layer: #¾²Ì¬µØÍ¼Ôø
 enabled: true


